# Generated by Django 4.2.14 on 2026-07-14 10:31

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import neighbourshare.gis_mock
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('tools', 'Tools'), ('garden_equipment', 'Garden Equipment'), ('kitchen_appliances', 'Kitchen Appliances'), ('electronics', 'Electronics'), ('sports_equipment', 'Sports Equipment'), ('musical_instruments', 'Musical Instruments'), ('cameras_photography', 'Cameras and Photography'), ('baby_children', 'Baby and Children'), ('books_stationery', 'Books and Stationery'), ('clothing_accessories', 'Clothing and Accessories'), ('furniture', 'Furniture'), ('vehicles_transport', 'Vehicles and Transport'), ('party_events', 'Party and Events'), ('cleaning_equipment', 'Cleaning Equipment'), ('medical_health', 'Medical and Health'), ('office_equipment', 'Office Equipment'), ('outdoor_camping', 'Outdoor and Camping'), ('other', 'Other')], max_length=30)),
                ('daily_rate_usd', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('deposit_amount_usd', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_available', models.BooleanField(default=True)),
                ('location', neighbourshare.gis_mock.MockPointField()),
                ('availability_calendar', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'items',
            },
        ),
        migrations.CreateModel(
            name='ItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='items/%Y/%m/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='items.item')),
            ],
            options={
                'db_table': 'item_images',
                'ordering': ['order'],
            },
        ),
    ]
