# Generated by Django 4.2.14 on 2026-07-14 10:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['location'], name='item_location_gist'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['category', 'is_available'], name='items_categor_c8602d_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['owner', 'is_available'], name='items_owner_i_9bd467_idx'),
        ),
    ]
