# Generated by Django 4.2.14 on 2026-07-26 14:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='daily_rate_usd',
        ),
        migrations.RemoveField(
            model_name='item',
            name='deposit_amount_usd',
        ),
        migrations.AddField(
            model_name='item',
            name='listing_type',
            field=models.CharField(choices=[('item', 'Physical Item'), ('service', 'Skill/Service')], default='item', max_length=10),
        ),
        migrations.AddField(
            model_name='item',
            name='tier',
            field=models.CharField(choices=[('tier_1', 'Tier 1 (Small Exchanges)'), ('tier_2', 'Tier 2 (Medium Exchanges)'), ('tier_3', 'Tier 3 (Large Exchanges)')], default='tier_1', max_length=10),
        ),
        migrations.AddField(
            model_name='item',
            name='time_credits_per_day',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='item',
            name='trade_request_details',
            field=models.TextField(blank=True, help_text='Description of what you want in return for specific trades'),
        ),
        migrations.AddField(
            model_name='item',
            name='trade_type',
            field=models.CharField(choices=[('specific_trade', 'Specific Trade Request'), ('open_offer', 'Open to Offers'), ('community_credit', 'Community Credit Only')], default='open_offer', max_length=20),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['tier', 'is_available'], name='items_tier_117ea6_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['trade_type', 'is_available'], name='items_trade_t_dad6f0_idx'),
        ),
    ]
