# Generated by Django 4.2.14 on 2026-07-14 10:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_condition', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('communication', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('punctuality', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('is_visible', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'ratings',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('DEPOSIT_HELD', 'Deposit Held'), ('ITEM_OUT', 'Item Out'), ('ITEM_RETURNED', 'Item Returned'), ('CLOSED', 'Closed'), ('DISPUTED', 'Disputed')], default='PENDING', max_length=20)),
                ('requested_from', models.DateField()),
                ('requested_to', models.DateField()),
                ('deposit_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('daily_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('escrow_reference', models.CharField(blank=True, max_length=100)),
                ('lender_scanned_handoff', models.BooleanField(default=False)),
                ('borrower_scanned_handoff', models.BooleanField(default=False)),
                ('lender_scanned_return', models.BooleanField(default=False)),
                ('borrower_scanned_return', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'transactions',
            },
        ),
        migrations.CreateModel(
            name='TransactionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('STATE_CHANGE', 'State Change'), ('QR_SCAN', 'QR Scan'), ('PAYMENT', 'Payment'), ('DISPUTE', 'Dispute'), ('RATING', 'Rating'), ('MESSAGE', 'Message')], max_length=20)),
                ('detail', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='transactions.transaction')),
            ],
            options={
                'db_table': 'transaction_events',
                'ordering': ['created_at'],
            },
        ),
    ]
