# Generated by Django 4.2.14 on 2026-07-14 10:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('items', '0002_initial'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='borrower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrowed_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transaction',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='items.item'),
        ),
        migrations.AddField(
            model_name='rating',
            name='ratee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rating',
            name='rater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings_given', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rating',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='transactions.transaction'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['borrower', 'state'], name='transaction_borrowe_de0147_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['item', 'state'], name='transaction_item_id_5d2645_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['state', 'updated_at'], name='transaction_state_e28139_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('transaction', 'rater')},
        ),
    ]
