# Generated by Django 4.2.14 on 2026-07-26 14:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transactions', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='daily_rate',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='deposit_amount',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='escrow_reference',
        ),
        migrations.AddField(
            model_name='transaction',
            name='handoff_condition',
            field=models.TextField(blank=True, help_text='Item condition recorded at hand-off'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='return_condition',
            field=models.TextField(blank=True, help_text='Item condition recorded at return'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='time_credits_per_day',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='transaction',
            name='total_time_credits',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rating',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='state',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('AGREED', 'Agreed'), ('ACTIVE', 'Active'), ('ITEM_OUT', 'Item Out'), ('ITEM_RETURNED', 'Item Returned'), ('CLOSED', 'Closed'), ('DISPUTED', 'Disputed')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='transactionevent',
            name='event_type',
            field=models.CharField(choices=[('STATE_CHANGE', 'State Change'), ('QR_SCAN', 'QR Scan'), ('TIME_CREDIT', 'Time Credit'), ('DISPUTE', 'Dispute'), ('RATING', 'Rating'), ('MESSAGE', 'Message')], max_length=20),
        ),
        migrations.AlterField(
            model_name='transactionevent',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='DisputeResolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('UNDER_REVIEW', 'Under Review'), ('PENDING_EVIDENCE', 'Pending Evidence'), ('RESOLVED', 'Resolved'), ('ESCALATED', 'Escalated')], default='OPEN', max_length=20)),
                ('outcome', models.CharField(blank=True, choices=[('LENDER_FAVOR', 'Lender Favor'), ('BORROWER_FAVOR', 'Borrower Favor'), ('SPLIT_CREDITS', 'Split Credits'), ('CANCELLED', 'Cancelled'), ('ESCALATED_EXTERNAL', 'Escalated to External')], max_length=30, null=True)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('evidence_summary', models.TextField(blank=True)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('first_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_disputes', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_disputes', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dispute_resolution', to='transactions.transaction')),
            ],
            options={
                'db_table': 'dispute_resolutions',
                'ordering': ['-opened_at'],
            },
        ),
    ]
