# Generated by Django 4.2.14 on 2026-08-15 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email_verified',
            field=models.BooleanField(default=False, help_text='Email confirmed via 6-digit verification code'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='registration_step',
            field=models.IntegerField(choices=[(0, 'Not Started'), (1, 'Account Created'), (2, 'Email Verified'), (3, 'ID Verified'), (4, 'Address Verified')], default=0),
        ),
    ]
